### ISSUE TITLE
Now that all-repos can read from an env var, is there any reason to use this plugin anymore?

### ISSUE THREAD

**Issue by jfly** [browniebroke/all-repos-envvar#469]
It looks like all-repos got support for reading from an env var last year: https://github.com/asottile/all-repos/commit/b3d2d9ef85b63284dc4e768cb5288ce36c222ee6.

Is there any reason for this project to still exist?

**Comment by browniebroke** [comment]
Oh I didn't realise it was added! Thanks for letting me know. 

The only thing that this plugin does which the built in implementation doesn't do (I think) is the ability to read from a `.env` file. So if you need that, it would be reason. I recall Anthony was quite strongly against the idea back when I started this extension...

**Comment by jfly** [comment]
> The only thing that this plugin does which the built in implementation doesn't do (I think) is the ability to read from a .env file

That makes sense! I personally prefer to use [direnv](https://direnv.net/) for that sort of thing, so I'll stick with vanilla all-repos.

> I recall Anthony was quite strongly against the idea back when I started this extension

Haha, yeah, he seemed pretty against it in https://github.com/asottile/all-repos/issues/79, but then merged up https://github.com/asottile/all-repos/pull/275 without much fanfare. :shrug:

I'll close this issue. You might want to update the part of your readme that says "I wanted this feature, but it looks like it won't be implemented in the main repo"

**Comment by browniebroke** [comment]
> You might want to update the part of your readme that says \"I wanted this feature, but it looks like it won't be implemented in the main repo\

Yes, I'll leave it open in the meantime 😊
